services:
  scribblepdf:
    build: .
    container_name: scribblepdf
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default-dev-key-please-change-in-production}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
      - ./app/static/processed:/app/app/static/processed
    restart: unless-stopped