services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB}
      - DEBUG=${DEBUG}
    restart: unless-stopped