services:
  scribblepdf:
    container_name: scribblepdf
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=AIzaSyC0-XP2icBGzvOY_JRzkuf2DV0wupBNu0A
      - SECRET_KEY=AIzaSyC0-XP2icBGzvOY_JRzkuf2DV0wupBNu0AAIzaSyC0-XP2icBGzvOY_JRzkuf2DV0wupBNu0A
    volumes:
      - .:/app
